In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
# Make plots display nicely
sns.set_theme(style="whitegrid")

# Show all columns
pd.set_option("display.max_columns", None)

In [4]:
df = pd.read_csv("../data/ACME-HappinessSurvey2020.csv")
os.listdir("../data")

['ACME-HappinessSurvey2020.csv']

In [8]:
#First few rows of the dataset
df.head()

   Y  X1  X2  X3  X4  X5  X6
0  0   3   3   3   4   2   4
1  0   3   2   3   5   4   3
2  1   5   3   3   3   3   5
3  0   5   4   3   3   3   5
4  0   5   4   3   3   3   5

In [10]:
#Dataset shape
df.shape

(126, 7)

In [11]:
#Columns
df.columns

Index(['Y', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6'], dtype='str')

In [12]:
#Dataset info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Y       126 non-null    int64
 1   X1      126 non-null    int64
 2   X2      126 non-null    int64
 3   X3      126 non-null    int64
 4   X4      126 non-null    int64
 5   X5      126 non-null    int64
 6   X6      126 non-null    int64
dtypes: int64(7)
memory usage: 7.0 KB

In [13]:
#Dataset description
df.describe()

,Y,X1,X2,X3,X4,X5,X6
count,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000
mean,0.547619,4.333333,2.531746,3.309524,3.746032,3.650794,4.253968
std,0.499714,0.800000,1.114892,1.023440,0.875776,1.147641,0.809311
min,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,0.000000,4.000000,2.000000,3.000000,3.000000,3.000000,4.000000
50%,1.000000,5.000000,3.000000,3.000000,4.000000,4.000000,4.000000
75%,1.000000,5.000000,3.000000,4.000000,4.000000,4.000000,5.000000
max,1.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [14]:
#check for missing values
df.isnull().sum()

Y     0
X1    0
X2    0
X3    0
X4    0
X5    0
X6    0
dtype: int64

In [22]:
#check for duplicate rows
duplicate_rows = df.duplicated().sum()
print(f"Duplicate rows: {duplicate_rows}")

#Note: 
# The dataset contains 16 duplicate rows 
# Should be investigated before model training.

Duplicate rows: 16

In [19]:
#determine the number of 1s and 0s in the target variable Y
df["Y"].value_counts()

Y
1    69
0    57
Name: count, dtype: int64

In [18]:
#determine the percentage of 1s and 0s in the target variable Y
df["Y"].value_counts(normalize=True) * 100

Y
1    54.761905
0    45.238095
Name: proportion, dtype: float64

In [21]:
#check that y values are only 1 or 0
#check that the X1 - X6 values are only 1 - 5
for col in df.columns:
    values = [int(x) for x in sorted(df[col].unique())]
    print(col, values)

Y [0, 1]
X1 [1, 3, 4, 5]
X2 [1, 2, 3, 4, 5]
X3 [1, 2, 3, 4, 5]
X4 [1, 2, 3, 4, 5]
X5 [1, 2, 3, 4, 5]
X6 [1, 2, 3, 4, 5]

In [23]:
df[df.duplicated()]

     Y  X1  X2  X3  X4  X5  X6
4    0   5   4   3   3   3   5
22   0   4   3   5   5   5   4
28   1   3   3   1   3   3   4
33   1   3   2   4   4   4   5
37   1   5   3   4   3   4   5
50   1   5   1   3   3   4   4
51   1   5   1   3   3   4   4
53   1   5   2   4   3   4   5
55   1   4   3   2   4   3   4
62   1   5   2   4   4   5   5
65   1   4   1   3   4   4   4
93   1   5   4   4   4   4   5
95   1   5   5   5   5   5   5
107  0   4   2   4   4   4   4
117  1   5   1   5   5   5   5
123  1   5   3   3   4   4   5