In [1]:
import pandas as pd

In [20]:
df = pd.read_csv("../data/ACME-HappinessSurvey2020.csv")
print(f"Number of duplicate rows: {len(df[df.duplicated()])}")
df = df.drop_duplicates()
print(f"Shape after removing duplicates: {df.shape}")

Number of duplicate rows: 16
Shape after removing duplicates: (110, 7)

In [ ]:
# split the dataset into features and target variable
X = df.drop("Y", axis=1)
y = df["Y"]

In [6]:
X.describe()

               X1          X2          X3          X4          X5          X6
count  110.000000  110.000000  110.000000  110.000000  110.000000  110.000000
mean     4.309091    2.536364    3.272727    3.736364    3.590909    4.209091
std      0.809864    1.106091    1.012845    0.895219    1.190909    0.836062
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000
25%      4.000000    2.000000    3.000000    3.000000    3.000000    4.000000
50%      4.500000    3.000000    3.000000    4.000000    4.000000    4.000000
75%      5.000000    3.000000    4.000000    4.000000    4.000000    5.000000
max      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000

In [21]:
df.corr()

           Y        X1        X2        X3        X4        X5        X6
Y   1.000000  0.286268 -0.000601  0.175445  0.076802  0.213360  0.137457
X1  0.286268  1.000000  0.059029  0.265379  0.100773  0.436698  0.405007
X2 -0.000601  0.059029  1.000000  0.203985  0.107055  0.056668 -0.102544
X3  0.175445  0.265379  0.203985  1.000000  0.262152  0.313917  0.170391
X4  0.076802  0.100773  0.107055  0.262152  1.000000  0.267937  0.221417
X5  0.213360  0.436698  0.056668  0.313917  0.267937  1.000000  0.307837
X6  0.137457  0.405007 -0.102544  0.170391  0.221417  0.307837  1.000000